export const MainData = [
  {
    id: 1,
    hostel: "Paras Boys Hostel",
    specs: `Rooms with Two single beds both AC\nand Non-AC boys`,
    Free: "Gym, Wifi,  cold purified water.",
    Paid: "AC, Mess.",
    Rent: "Rs. 4000/month",

    hostel_img: "../public/images/living/image 1.png",
    contactImg: "../public/images/living/6596115 1.png",
    addressImg: "../public/images/living/447031 1.png",
    mediaImg: "../public/images/living/3178404 1.png",
    reviewImg: "../public/images/living/satisfaction.png",
  },
  {
    id: 2,
    hostel: "Shamilar Boys Hostel",
    specs: `Rooms with Two single beds both AC\nand Non-AC boys`,
    Free: "Gym, Wifi,  cold purified water.",
    Paid: "AC, Mess.",
    Rent: "Rs. 4000/month",
    hostel_img: "../public/images/living/image 1.png",
    contactImg: "../public/images/living/6596115 1.png",
    addressImg: "../public/images/living/447031 1.png",
    mediaImg: "../public/images/living/3178404 1.png",
    reviewImg: "../public/images/living/satisfaction.png",
  },
  {
    id: 3,
    hostel: "Unity Boys Hostel",
    specs: `Rooms with Two single beds both AC\nand Non-AC boys`,
    Free: "Gym, Wifi,  cold purified water.",
    Paid: "AC, Mess.",
    Rent: "Rs. 3500 - 7000/month",
    hostel_img: "../public/images/living/image 1.png",
    contactImg: "../public/images/living/6596115 1.png",
    addressImg: "../public/images/living/447031 1.png",
    mediaImg: "../public/images/living/3178404 1.png",
    reviewImg: "../public/images/living/satisfaction.png",
  },
  {
    id: 4,
    hostel: "Regal Residence Girls",
    specs: `Rooms with Two single beds both AC\nand Non-AC girls`,
    Free: "Gym, Wifi,  cold purified water.",
    Paid: "AC, Mess.",

    Rent: "Rs.3500-7000/month",
    hostel_img: "../public/images/living/image 1.png",
    contactImg: "../public/images/living/6596115 1.png",
    addressImg: "../public/images/living/447031 1.png",
    mediaImg: "../public/images/living/3178404 1.png",
    reviewImg: "../public/images/living/satisfaction.png",
  },
  {
    id: 5,
    hostel: "Paradise Girls Hostel",
    specs: `Rooms with Two single beds both AC\nand Non-AC girls`,
    Free: " Wifi,  cold purified water.",
    Paid: "AC, Mess.",

    Rent: "Rs. 3500/month",
    hostel_img: "../public/images/living/image 1.png",
    contactImg: "../public/images/living/6596115 1.png",
    addressImg: "../public/images/living/447031 1.png",
    mediaImg: "../public/images/living/3178404 1.png",
    reviewImg: "../public/images/living/satisfaction.png",
  },
  {
    id: 6,
    hostel: "Nadim House",
    specs: `Rooms with Two single beds both AC\nand Non-AC boys`,
    Free: "Gym, Wifi,  cold purified water.",
    Paid: "AC, Mess.",

    Rent: "Rs. 2200/month",
    hostel_img: "../public/images/living/image 1.png",
    contactImg: "../public/images/living/6596115 1.png",
    addressImg: "../public/images/living/447031 1.png",
    mediaImg: "../public/images/living/3178404 1.png",
    reviewImg: "../public/images/living/satisfaction.png",
  },
  {
    id: 7,
    hostel: "New Boys Hostel",
    specs: `Rooms with Two single beds both AC\nand Non-AC`,
    Free: "Gym, Wifi,  cold purified water.",
    Paid: "AC, Mess.",

    Rent: "Rs. 2200-2500/month",
    hostel_img: "../public/images/living/image 1.png",
    contactImg: "../public/images/living/6596115 1.png",
    addressImg: "../public/images/living/447031 1.png",
    mediaImg: "../public/images/living/3178404 1.png",
    reviewImg: "../public/images/living/satisfaction.png",
  },
  {
    id: 8,
    hostel: "Ayaan Boys Hostel",
    specs: `Rooms with Two single beds both AC\nand Non-AC`,
    Free: "Gym, Wifi,  cold purified water.",
    Paid: "AC, Mess.",

    Rent: "Rs. 2500/month",
    hostel_img: "../public/images/living/image 1.png",
    contactImg: "../public/images/living/6596115 1.png",
    addressImg: "../public/images/living/447031 1.png",
    mediaImg: "../public/images/living/3178404 1.png",
    reviewImg: "../public/images/living/satisfaction.png",
  },
  {
    id: 9,
    hostel: "Zee Girls Hostel",
    specs: `Rooms with Two single beds both AC\nand Non-AC girls`,
    Free: "Gym, Wifi,  cold purified water.",
    Paid: "AC, Mess.",

    Rent: "Rs.2500-3000/month",
    hostel_img: "../public/images/living/image 1.png",
    contactImg: "../public/images/living/6596115 1.png",
    addressImg: "../public/images/living/447031 1.png",
    mediaImg: "../public/images/living/3178404 1.png",
    reviewImg: "../public/images/living/satisfaction.png",
  },
  {
    id: 10,
    hostel: "She Rose Girls Hostel",
    specs: `Rooms with Two single beds both AC\nand Non-AC girls`,
    Free: "Gym, Wifi,  cold purified water.",
    Paid: "AC, Mess.",

    Rent: "Rs. 4000/month",
    hostel_img: "../public/images/living/image 1.png",
    contactImg: "../public/images/living/6596115 1.png",
    addressImg: "../public/images/living/447031 1.png",
    mediaImg: "../public/images/living/3178404 1.png",
    reviewImg: "../public/images/living/satisfaction.png",
  },
  {
    id: 10,
    hostel: "She Rose Girls Hostel",
    specs: `Rooms with Two single beds both AC\nand Non-AC girls`,
    Free: "Gym, Wifi,  cold purified water.",
    Paid: "AC, Mess.",

    Rent: "Rs. 4000/month",
    hostel_img: "../public/images/living/image 1.png",
    contactImg: "../public/images/living/6596115 1.png",
    addressImg: "../public/images/living/447031 1.png",
    mediaImg: "../public/images/living/3178404 1.png",
    reviewImg: "../public/images/living/satisfaction.png",
  },
];
