export const MainData = [
  {
    id: 1,
    hostel: "Paras Boys Hostel",
    specs: `Rooms with Two single beds both AC\nand Non-AC boys`,
    Free: "Gym, Wifi,  cold purified water.",
    Paid: "AC, Mess.",
    Rent: "Rs. 3500-4000/month",
    hostel_img: "/images/living/image 1.png",
    contactImg: "/images/living/6596115 1.png",
    phone1: "+917275807178",
    contactPerson: "Vinod",
    addressImg: "/images/living/447031 1.png",
    map: `https://www.google.com/maps/place/Paras+Boys+Hostel+-+Kursi+Road/@26.9548321,80.9956039,17z/data=!4m14!1m7!3m6!1s0x399959b537a27ce7:0xc3b1179e1579e014!2sParas+Boys+Hostel+-+Kursi+Road!8m2!3d26.9548273!4d80.9981788!16s%2Fg%2F11fn5sp32z!3m5!1s0x399959b537a27ce7:0xc3b1179e1579e014!8m2!3d26.9548273!4d80.9981788!16s%2Fg%2F11fn5sp32z?entry=ttu
    `,
    mediaImg: "/images/living/3178404 1.png",
    reviewImg: "/images/living/satisfaction.png",
  },
  {
    id: 2,
    hostel: "Shamilar Boys Hostel",
    specs: `Rooms with Two single beds for boys`,
    Free: "cold purified water, gyser",
    Paid: "Mess , cooler",
    Rent: "Rs. 2000-2200/month",
    hostel_img: "/images/living/image 1.png",
    contactImg: "/images/living/6596115 1.png",
    phone1: "+919554472777",
    contactPerson: " Mohd Salim ",
    map: `https://www.google.com/maps/dir//XX4X%2BJ49+Shalimar+Boys+Hostel+Kursi+Road+Lucknow,+Lucknow,+Uttar+Pradesh+226026/@26.95655,80.9952898,17z/data=!4m8!4m7!1m0!1m5!1m1!1s0x399959e7fc01ead7:0x643ac12cc828ea56!2m2!1d80.9978663!2d26.9565444?entry=ttu
    `,
    addressImg: "/images/living/447031 1.png",
    mediaImg: "/images/living/3178404 1.png",
    reviewImg: "/images/living/satisfaction.png",
  },
  {
    id: 3,
    hostel: "Unity Boys Hostel",
    specs: `Rooms with Two single beds Non-AC boys`,
    Free: " cold purified water , gyser , lift",
    Paid: "AC, Mess.",
    Rent: "Contact to owner",
    hostel_img: "/images/living/image 1.png",
    contactImg: "/images/living/6596115 1.png",
    phone1: "+919170763907",
    phone2: "+919119884568",
    contactPerson: "Arshad / Nadim ",
    addressImg: "/images/living/447031 1.png",
    mediaImg: "/images/living/3178404 1.png",
    reviewImg: "/images/living/satisfaction.png",
  },
  {
    id: 4,
    hostel: "Regal Residence Girls",
    specs: `Rooms with Two single beds both AC\nand Non-AC girls`,
    Free: " Wifi, cold purified water ",
    Paid: "AC, Electricity",
    Rent: "Rs.3500-7000/month",
    hostel_img: "/images/living/image 1.png",
    contactImg: "/images/living/6596115 1.png",
    phone1: "+917518471163",
    phone2: "+918800652669",
    contactPerson: "Aneeqa Rehman",
    addressImg: "/images/living/447031 1.png",
    mediaImg: "/images/living/3178404 1.png",
    reviewImg: "/images/living/satisfaction.png",
  },
  {
    id: 5,
    hostel: "Paradise Girls Hostel",
    specs: `Rooms with Two single beds Non-AC girls`,
    Free: " Wifi,  cold purified water , gyser",
    Paid: " NA",
    Rent: "Rs. 3500/month",
    hostel_img: "/images/living/image 1.png",
    contactImg: "/images/living/6596115 1.png",
    phone1: "+918090208280",
    contactPerson: "Junaid Khan",

    addressImg: "/images/living/447031 1.png",
    mediaImg: "/images/living/3178404 1.png",
    reviewImg: "/images/living/satisfaction.png",
  },
  {
    id: 6,
    hostel: "Infront of Royal Hostel",
    specs: `Rooms with Two/Three single beds Non-AC boys`,
    Free: "cold purified water , gyser",
    Paid: "Cooler",
    Rent: "Rs. 2200-2700/month ",
    hostel_img: "/images/living/image 1.png",
    contactImg: "/images/living/6596115 1.png",
    phone1: "+919321072432",
    contactPerson: "Bunty",

    addressImg: "/images/living/447031 1.png",
    mediaImg: "/images/living/3178404 1.png",
    reviewImg: "/images/living/satisfaction.png",
  },
  {
    id: 7,
    hostel: "Arsh Tower",
    specs: `Rooms with Two/Three single beds Non-AC`,
    Free: "Wifi, cold purified water , gyser",
    Paid: "Cooler",
    Rent: "Rs. 2800-3000/month",
    hostel_img: "/images/living/image 1.png",
    contactImg: "/images/living/6596115 1.png",
    phone1: "+919793078323",
    contactPerson: "Firoj W Khan",

    addressImg: "/images/living/447031 1.png",
    mediaImg: "/images/living/3178404 1.png",
    reviewImg: "/images/living/satisfaction.png",
  },
  {
    id: 8,
    hostel: "Royal Boys Hostel",
    specs: `Rooms with Two single beds Non-AC`,
    Free: " cold purified water , gyser",
    Paid: "Cooler, Mess.",
    Rent: "Rs. 2500/month",
    hostel_img: "/images/living/image 1.png",
    contactImg: "/images/living/6596115 1.png",
    phone1: "NA",
    contactPerson: "Arif",

    addressImg: "/images/living/447031 1.png",
    mediaImg: "/images/living/3178404 1.png",
    reviewImg: "/images/living/satisfaction.png",
  },
  {
    id: 9,
    hostel: "She Rose Girls Hostel",
    specs: `Rooms with Two single beds both AC\nand Non-AC girls`,
    Free: " Wifi,  cold purified water.",
    Paid: "AC, Mess.",
    Rent: "For AC - Rs.8500/month\n Non AC - Rs.5500/month",
    hostel_img: "/images/living/image 1.png",
    contactImg: "/images/living/6596115 1.png",
    phone1: "+917457944338",
    contactPerson: "Shivani",

    addressImg: "/images/living/447031 1.png",
    mediaImg: "/images/living/3178404 1.png",
    reviewImg: "/images/living/satisfaction.png",
  },
  {
    id: 10,
    hostel: "Zee Girls Hostel",
    specs: `Rooms with Two single beds for girls`,
    Free: " cold purified water., gyser",
    Paid: "Cooler ,Mess.",
    Rent: "Rs. 2500-3000/month",
    hostel_img: "/images/living/image 1.png",
    contactImg: "/images/living/6596115 1.png",
    phone1: "+916394091240",
    contactPerson: "Mohd Arif",

    addressImg: "/images/living/447031 1.png",
    mediaImg: "/images/living/3178404 1.png",
    reviewImg: "/images/living/satisfaction.png",
  },
  {
    id: 10,
    hostel: "Al- Musharrat Boys Hostel",
    specs: `Rooms with Two single beds for Boys`,
    Free: " cold purified water , gyser",
    Paid: " Mess.",
    Rent: "Rs. 2500/month",
    hostel_img: "/images/living/image 1.png",
    contactImg: "/images/living/6596115 1.png",
    phone1: "NA",
    contactPerson: "Balgovind",

    addressImg: "/images/living/447031 1.png",
    mediaImg: "/images/living/3178404 1.png",
    reviewImg: "/images/living/satisfaction.png",
  },
  {
    id: 11,
    hostel: "Verma Height Boys Hostel",
    specs: `Rooms with Two single beds with kitchen`,
    Free: " cold purified water , gyser",
    Paid: " Mess.",
    Rent: "Rs. 2500 -4000/month",
    hostel_img: "/images/living/image 1.png",
    phone1: "+917905130026",
    contactPerson: "Aadarsh Patel",

    contactImg: "/images/living/6596115 1.png",
    addressImg: "/images/living/447031 1.png",
    mediaImg: "/images/living/3178404 1.png",
    reviewImg: "/images/living/satisfaction.png",
  },
  {
    id: 12,
    hostel: "St.Xavier Boys Hostel",
    specs: `Rooms with Two single beds for Boys`,
    Free: " cold purified water , gyser",
    Paid: " Mess.",
    Rent: "Rs. 2700/month",
    hostel_img: "/images/living/image 1.png",
    contactImg: "/images/living/6596115 1.png",
    phone1: "+919455882348",
    phone2: "+91902682818",
    contactPerson: "Bimal Kumar",

    addressImg: "/images/living/447031 1.png",
    mediaImg: "/images/living/3178404 1.png",
    reviewImg: "/images/living/satisfaction.png",
  },
  {
    id: 13,
    hostel: "Krishna Boys Hostel / PG",
    specs: `Rooms with Two single beds for Boys`,
    Free: " Wifi ,cold purified water , gyser",
    Paid: " Mess.",
    Rent: "Rs. 5000-5500/month",
    hostel_img: "/images/living/image 1.png",
    contactImg: "/images/living/6596115 1.png",
    phone1: "+917905640993",
    contactPerson: "Satender",

    addressImg: "/images/living/447031 1.png",
    mediaImg: "/images/living/3178404 1.png",
    reviewImg: "/images/living/satisfaction.png",
  },
  {
    id: 14,
    hostel: "National Girls Hostel",
    specs: `Rooms with Two single beds for Girls`,
    Free: " Wifi ,cold purified water , gyser",
    Paid: " Mess.",
    Rent: "Rs. NA/month",
    phone1: "NA ",
    contactPerson: " NA",
    hostel_img: "/images/living/image 1.png",
    contactImg: "/images/living/6596115 1.png",
    addressImg: "/images/living/447031 1.png",
    mediaImg: "/images/living/3178404 1.png",
    reviewImg: "/images/living/satisfaction.png",
  },
  {
    id: 15,
    hostel: "Infinity Tower ",
    specs: `Rooms with Two single beds for Boys`,
    Free: " cold purified water , gyser",
    Paid: " Electricity",
    Rent: "Rs. NA/month",
    hostel_img: "/images/living/image 1.png",
    contactImg: "/images/living/6596115 1.png",
    phone1: "NA",
    contactPerson: "Shah Alam",

    addressImg: "/images/living/447031 1.png",
    mediaImg: "/images/living/3178404 1.png",
    reviewImg: "/images/living/satisfaction.png",
  },
  {
    id: 16,
    hostel: "Trivedi Tower",
    specs: `Rooms with Two single beds for Boys`,
    Free: " cold purified water , gyser",
    Paid: " AC",
    Rent: "Rs. 3000/month",
    hostel_img: "/images/living/image 1.png",
    contactImg: "/images/living/6596115 1.png",
    phone1: "+919918585192",
    contactPerson: "Rohit / Trivedi",

    addressImg: "/images/living/447031 1.png",
    mediaImg: "/images/living/3178404 1.png",
    reviewImg: "/images/living/satisfaction.png",
  },
  {
    id: 17,
    hostel: "Makan Boys Hostel",
    specs: `Rooms with Two single beds for Boys`,
    Free: " cold purified water , gyser",
    Paid: " Mess.",
    Rent: "Rs. 2500-3000/month",
    hostel_img: "/images/living/image 1.png",
    contactImg: "/images/living/6596115 1.png",
    phone1: "+919889228933",

    addressImg: "/images/living/447031 1.png",
    mediaImg: "/images/living/3178404 1.png",
    reviewImg: "/images/living/satisfaction.png",
  },
  {
    id: 18,
    hostel: "KN Boys Hostel",
    specs: `Rooms with Two single beds for Boys`,
    Free: " cold purified water , gyser",
    Paid: " Mess.",
    Rent: "Rs. 2000/month",
    hostel_img: "/images/living/image 1.png",
    contactImg: "/images/living/6596115 1.png",
    phone1: "NA",
    contactPerson: "Atikur Rehman",

    addressImg: "/images/living/447031 1.png",
    mediaImg: "/images/living/3178404 1.png",
    reviewImg: "/images/living/satisfaction.png",
  },
  {
    id: 19,
    hostel: "Cafeteria",
    specs: `Rooms with Two single beds for Boys`,
    Free: " cold purified water , gyser",
    Paid: " Mess.",
    Rent: "Rs. 2500/month",
    hostel_img: "/images/living/image 1.png",
    contactImg: "/images/living/6596115 1.png",
    phone1: "NA",
    contactPerson: "NA",

    addressImg: "/images/living/447031 1.png",
    mediaImg: "/images/living/3178404 1.png",
    reviewImg: "/images/living/satisfaction.png",
  },
  {
    id: 20,
    hostel: "New Sainik Hostel",
    specs: `Rooms with Two single beds for Boys`,
    Free: " cold purified water , gyser",
    Paid: " Mess.",
    Rent: "Rs. 2500/month",
    hostel_img: "/images/living/image 1.png",
    contactImg: "/images/living/6596115 1.png",
    phone1: "+917235087989",
    contactPerson: "Wahid Ahmad",

    addressImg: "/images/living/447031 1.png",
    mediaImg: "/images/living/3178404 1.png",
    reviewImg: "/images/living/satisfaction.png",
  },
  {
    id: 21,
    hostel: "NP Boys Hostel",
    specs: `Rooms with Two single beds for Boys`,
    Free: " cold purified water , gyser",
    Paid: " Mess.",
    Rent: "Rs. 1200-1500/month",
    hostel_img: "/images/living/image 1.png",
    contactImg: "/images/living/6596115 1.png",
    phone1: "+917459833635",
    contactPerson: "Ritik",

    addressImg: "/images/living/447031 1.png",
    mediaImg: "/images/living/3178404 1.png",
    reviewImg: "/images/living/satisfaction.png",
  },
  {
    id: 22,
    hostel: "Galaxy Boys Hostel",
    specs: `Rooms with Two single beds for Boys`,
    Free: " cold purified water ",
    Paid: " Mess.",
    Rent: "Rs. 2000/month",
    hostel_img: "/images/living/image 1.png",
    contactImg: "/images/living/6596115 1.png",
    phone1: "NA",
    contactPerson: "Sadab Khan",

    addressImg: "/images/living/447031 1.png",
    mediaImg: "/images/living/3178404 1.png",
    reviewImg: "/images/living/satisfaction.png",
  },
  {
    id: 23,
    hostel: "Salman Boys Hostel",
    specs: `Rooms with Two single beds for Boys`,
    Free: " cold purified water",
    Paid: " Mess.",
    Rent: "Rs. 2500/month",
    hostel_img: "/images/living/image 1.png",
    contactImg: "/images/living/6596115 1.png",
    phone1: "+918429825742",
    contactPerson: "Salman",

    addressImg: "/images/living/447031 1.png",
    mediaImg: "/images/living/3178404 1.png",
    reviewImg: "/images/living/satisfaction.png",
  },
  {
    id: 24,
    hostel: "Vidya Boys Hostel",
    specs: `Rooms with Two/Three single beds for Boys`,
    Free: " cold purified water , gyser",
    Paid: " Mess.",
    Rent: "Rs. 2500/month",
    hostel_img: "/images/living/image 1.png",
    contactImg: "/images/living/6596115 1.png",
    phone1: "+919651891781",
    contactPerson: "Deepu Singh",

    addressImg: "/images/living/447031 1.png",
    mediaImg: "/images/living/3178404 1.png",
    reviewImg: "/images/living/satisfaction.png",
  },
  {
    id: 25,
    hostel: "Nadeem Boys Hostel",
    specs: `Rooms with Twosingle beds for Boys`,
    Free: " cold purified water , gyser",
    Paid: " Mess.",
    Rent: "Rs. 2200/month",
    hostel_img: "/images/living/image 1.png",
    contactImg: "/images/living/6596115 1.png",
    phone1: "+919044858636",
    contactPerson: "Yakub",

    addressImg: "/images/living/447031 1.png",
    mediaImg: "/images/living/3178404 1.png",
    reviewImg: "/images/living/satisfaction.png",
  },
  {
    id: 25,
    hostel: "New Boys Hostel",
    specs: `Rooms with Two single beds for Boys`,
    Free: " cold purified water , gyser",
    Paid: " Mess.",
    Rent: "Rs. 2200/month",
    hostel_img: "/images/living/image 1.png",
    contactImg: "/images/living/6596115 1.png",
    phone1: "+918881621195",
    contactPerson: "Faisal",
    addressImg: "/images/living/447031 1.png",
    mediaImg: "/images/living/3178404 1.png",
    reviewImg: "/images/living/satisfaction.png",
  },
  {
    id: 26,
    hostel: "Ayaan Boys Hostel",
    specs: `Rooms with Two single beds for Boys`,
    Free: " cold purified water , gyser",
    Paid: " Mess.",
    Rent: "Rs. 2500/month",
    hostel_img: "/images/living/image 1.png",
    contactImg: "/images/living/6596115 1.png",
    phone1: "NA",
    contactPerson: "Ali Samad",

    addressImg: "/images/living/447031 1.png",
    mediaImg: "/images/living/3178404 1.png",
    reviewImg: "/images/living/satisfaction.png",
  },
  {
    id: 27,
    hostel: "Gazi Boys Hostel",
    specs: `Rooms with Two single beds for Boys with kitchen`,
    Free: " cold purified water , gyser",
    Paid: " Mess.",
    Rent: "Rs. 2000/month",
    hostel_img: "/images/living/image 1.png",
    contactImg: "/images/living/6596115 1.png",
    phone1: "+919984919986",
    contactPerson: "Osama Gazi",

    addressImg: "/images/living/447031 1.png",
    mediaImg: "/images/living/3178404 1.png",
    reviewImg: "/images/living/satisfaction.png",
  },
  {
    id: 28,
    hostel: "Meraj Boys Hostel",
    specs: `Rooms with Two single beds for Boys`,
    Free: " cold purified water , gyser",
    Paid: " Mess.",
    Rent: "NA",
    hostel_img: "/images/living/image 1.png",
    contactImg: "/images/living/6596115 1.png",
    phone1: "+919005531897",
    contactPerson: "Kurban Khan",

    addressImg: "/images/living/447031 1.png",
    mediaImg: "/images/living/3178404 1.png",
    reviewImg: "/images/living/satisfaction.png",
  },
  {
    id: 29,
    hostel: "Apartment Near Meraj Hostel",
    specs: `Two Rooms with balcony for Boys`,
    Free: " cold purified water ",
    Paid: " Electricity",
    Rent: "Rs. 13K-15K/month",
    hostel_img: "/images/living/image 1.png",
    contactImg: "/images/living/6596115 1.png",
    phone1: "+916388115518",
    contactPerson: "Seraj / Asif",
    addressImg: "/images/living/447031 1.png",
    mediaImg: "/images/living/3178404 1.png",
    reviewImg: "/images/living/satisfaction.png",
  },
  {
    id: 30,
    hostel: "Anwar Hostel",
    specs: `Rooms with Two single beds for Boys And Girls`,
    Free: " cold purified water , gyser",
    Paid: " Mess.",
    Rent: "Rs. 2000/month",
    hostel_img: "/images/living/image 1.png",
    contactImg: "/images/living/6596115 1.png",
    phone1: "+919721402230",
    contactPerson: "Anwar",

    addressImg: "/images/living/447031 1.png",
    mediaImg: "/images/living/3178404 1.png",
    reviewImg: "/images/living/satisfaction.png",
  },
  {
    id: 31,
    hostel: "Rehman Boys Hostel",
    specs: `Rooms with Two single beds for Boys`,
    Free: " cold purified water , gyser",
    Paid: " Mess.",
    Rent: "Rs. 2200/month",
    hostel_img: "/images/living/image 1.png",
    contactImg: "/images/living/6596115 1.png",
    phone1: "+918470935838",
    contactPerson: "Irfan",

    addressImg: "/images/living/447031 1.png",
    mediaImg: "/images/living/3178404 1.png",
    reviewImg: "/images/living/satisfaction.png",
  },
  {
    id: 32,
    hostel: "Siddiqui Boys Hostel",
    specs: `Rooms with Two single beds for Boys`,
    Free: " cold purified water , gyser",
    Paid: " Mess.",
    Rent: "Rs. 2200/month",
    hostel_img: "/images/living/image 1.png",
    contactImg: "/images/living/6596115 1.png",
    phone1: "+919984842438",
    phone2: "+918470935838",
    contactPerson: "Irfan",

    addressImg: "/images/living/447031 1.png",
    mediaImg: "/images/living/3178404 1.png",
    reviewImg: "/images/living/satisfaction.png",
  },
  {
    id: 33,
    hostel: "Fauji Boys Hostel",
    specs: `Rooms with Two single beds for Boys`,
    Free: " cold purified water , gyser",
    Paid: " Mess , Wifi",
    Rent: "Rs. 2500-3000/month",
    hostel_img: "/images/living/image 1.png",
    contactImg: "/images/living/6596115 1.png",
    phone1: "+919670440392",

    addressImg: "/images/living/447031 1.png",
    mediaImg: "/images/living/3178404 1.png",
    reviewImg: "/images/living/satisfaction.png",
  },
];
