export const MainData = [
    {
      id: 1,
      shopPlace: "Super Store & Bakers",
      specs: "One place for every grocery",
      serviceOptions: "Groceries, Health and Beauty, Food and Beverage",
      timings: "10:00 am - 10:00 pm",
      shopPlace_img: "/images/living/image 1.png",
      contactImg: "/images/living/6596115 1.png",
      addressImg: "/images/living/447031 1.png",
      mediaImg: "/images/living/3178404 1.png",
      reviewImg: "/images/living/satisfaction.png",
    },
    {
      id: 2,
      shopPlace: "Meraj General Store",
      specs: "One place for every grocery",
      serviceOptions: "Groceries, Health and Beauty, Food and Beverage",
      timings: "10:00 am - 10:00 pm",
      shopPlace_img: "/images/living/image 1.png",
      contactImg: "/images/living/6596115 1.png",
      addressImg: "/images/living/447031 1.png",
      mediaImg: "/images/living/3178404 1.png",
      reviewImg: "/images/living/satisfaction.png",
    },
    {
      id: 3,
      shopPlace: "Sunil General Store",
      specs: "One place for every grocery",
      serviceOptions: "Groceries, Health and Beauty, Food and Beverage",
      timings: "10:00 am - 10:00 pm",
      shopPlace_img: "/images/living/image 1.png",
      contactImg: "/images/living/6596115 1.png",
      addressImg: "/images/living/447031 1.png",
      mediaImg: "/images/living/3178404 1.png",
      reviewImg: "/images/living/satisfaction.png",
    },
  ];
  