export const MainData = [
    {
      id: 1,
      emerPlace: "Vinod Medical Store",
      specs: "Buy any medicine at any time",
      serviceOptions: "Medicines, cosmetics, medical equipments",
      timings: "9:00 am to 11:30 pm",
      emerPlace_img: "/images/living/image 1.png",
      contactImg: "/images/living/6596115 1.png",
      addressImg: "/images/living/447031 1.png",
      mediaImg: "/images/living/3178404 1.png",
      reviewImg: "/images/living/satisfaction.png",
    },
    {
        id: 3,
        emerPlace: "Vinod Medical Store",
        specs: "Buy any medicine at any time",
        serviceOptions: "Medicines, cosmetics, medical equipments",
        timings: "9:00 am to 11:30 pm",
        emerPlace_img: "/images/living/image 1.png",
        contactImg: "/images/living/6596115 1.png",
        addressImg: "/images/living/447031 1.png",
        mediaImg: "/images/living/3178404 1.png",
        reviewImg: "/images/living/satisfaction.png",
      },
      {
        id: 2,
        emerPlace: "Vinod Medical Store",
        specs: "Buy any medicine at any time",
        serviceOptions: "Medicines, cosmetics, medical equipments",
        timings: "9:00 am to 11:30 pm",
        emerPlace_img: "/images/living/image 1.png",
        contactImg: "/images/living/6596115 1.png",
        addressImg: "/images/living/447031 1.png",
        mediaImg: "/images/living/3178404 1.png",
        reviewImg: "/images/living/satisfaction.png",
      },
  ];
  