export const MainData = [
    {
      id: 1,
      foodPlace: "Dreams Dhaba",
      specs: `Dinings with Private curtains rooms and a village like feel`,
      priceRange: "Rs. 200 - 400/person",
      serviceOptions: "Dining and Takeaway",
      timings: "11:00 am - 11:00 pm",
      foodPlace_img: "/images/living/image 1.png",
      contactImg: "/images/living/6596115 1.png",
      addressImg: "/images/living/447031 1.png",
      mediaImg: "/images/living/3178404 1.png",
      reviewImg: "/images/living/satisfaction.png",
    },
    {
      id: 2,
      foodPlace: "MahaChai Restaurant",
      specs: `Dinings with both private and public sittings`,
      priceRange: "Rs. 20 - 200/person",
      serviceOptions: "Dinings, Takeaways and Delivery",
      timings: "10:00 am - 9:00 pm",
      foodPlace_img: "/images/living/image 1.png",
      contactImg: "/images/living/6596115 1.png",
      addressImg: "/images/living/447031 1.png",
      mediaImg: "/images/living/3178404 1.png",
      reviewImg: "/images/living/satisfaction.png",
    },
    {
      id: 3,
      foodPlace: "Pizza Room Restaurant",
      specs: `Fully Furnished dinings with an ambient look`,
      priceRange: "Rs. 150 - 500/person",
      serviceOptions: "Dine-in/Dine-through",
      timings: "10:00 am - 10:00 pm",
      foodPlace_img: "/images/living/image 1.png",
      contactImg: "/images/living/6596115 1.png",
      addressImg: "/images/living/447031 1.png",
      mediaImg: "/images/living/3178404 1.png",
      reviewImg: "/images/living/satisfaction.png",
    },
]